### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by Caellian** [BuiltBrokenModding/BBM-MFFS#2]
This code can't be distributed as a compiled mod until Calclavia gives you explicit permission to distribute it.

If you're going to completely ignore that Calclavia has to give you permission to actually rewrite his code, you still have to use his educational public license which prevents you from requiring players to beg for your permission in order to add this mod to their modpacks.

It makes me really sad to see the way you've butchered both calclavias mod and his general principles about open software.

Love, Caellian, xoxo.

**Comment by Strikingwolf** [comment]
I agree, except on the last part, I just hope you learn to stop blatantly stealing other people's work without permission

**Comment by DarkGuardsman** [comment]
I have full permission from Calclavia to work on this project, the repo is also the original repo from calclavia himself. Not that I needed his permission since I was a founder of Universal Electricity team which had ownership of the port.

**Comment by Caellian** [comment]
Okay then.

**Comment by DarkGuardsman** [comment]
:/ please check your facts before accusing people, it would have been really easy to check that I worked with calclavia for 3+ years. As well that I had code in the project going back just as long.

**Comment by Caellian** [comment]
I misunderstood the situation because this project had the forked readme file and saw BBM as owner.
Well... this is awkward. Sorry.

**Comment by DarkGuardsman** [comment]
:) it's no problem this has happened before with other projects that calclavia has given me. The name is different because we original only had permission to make our own port. Now we basically own the original mod and the ability to work on it. So long as calclavia doesn't request for it back, which we will work out later if he ever comes back to modding.

**Comment by Maxwolf** [comment]
![tinsvageljismean](https://cloud.githubusercontent.com/assets/6830398/17163032/16322866-5370-11e6-891b-d93dedf023c1.jpg)

I like how you edited your message to remove your hateful and mean spirited message. It is that type of toxic attitude that makes the modding community so hard to work in and stifles innovation and prevents cool things from being made.

You sir are not only mean, but you were wrong. Next time try talking about things in a civil manner, and don't edit your posts because this is the Internet... and we know what you did.

**Comment by Caellian** [comment]
@Maxwolf I edited the post because I got carried away. It's hard to explain to someone who doesn't know me personally, but I didn't mean what I said in that sentence (Sady Saxton reference - note "Love, Cael, xoxo" at the end). I later realised it was over the top and that you will understand me as being serious so I edited it.

I wish you luck with this project and I'm terribly sorry for attacking like that.

**Comment by DarkGuardsman** [comment]
@Maxwolf  Ya I saw the original message but ignored it. Most people can get upset and normally calm down later. 

@Caellian Thank you for editing it, and realizing your mistake :) . At least it didn't turn into one of the flame wars that I saw Reika go threw a few months back.

**Comment by dmodoomsirius** [comment]
Locking issue since everyone is calm and everything is resolved.
