### ISSUE TITLE
Caught exception from mffs java.lang.NoClassDefFoundError: javax/vecmath/Vector2d

### ISSUE THREAD

**Issue by BrokenFire** [BuiltBrokenModding/BBM-MFFS#33]
Hey ! 

I have a little probleme whit the  28-unversal version on my server, on client the mod work fine but on server, it crash whit this 

`java.lang.NoClassDefFoundError: javax/vecmath/Vector2d`

My log:
http://pastebin.com/DGDM2DgR

Broken_Fire from france !

**Comment by DarkGuardsman** [comment]
I want to assume this issue is on @Pwalne (aka Poopsicle) version of the mod so he will need to handle it. Plus he is in charge of the mod for the moment until I have time to work on it again. The issue, however, looks strait forward and is a bad import. Most likely you could install a different version of java as I assume your using linux on the server side and it does not include javafx by default.

`java.lang.NoClassDefFoundError: javax/vecmath/Vector2d
	at com.mffs.common.tile.TileFieldMatrix.<clinit>(TileFieldMatrix.java:29) ~[TileFieldMatrix.class:1.7.10-5.1.0b20161018180309]

https://github.com/Pwalne/mc_mffs/blob/master/src/main/java/com/mffs/common/tile/TileFieldMatrix.java#L18`

**Comment by BrokenFire** [comment]
Ah ok,

But today i try to launch my serveur on windows with Java8 (JavaFx is implemented on it now ?) and i have the same error.

So now, I don't understand why, on the same computer, client work fine but server crash.....

I think my Java practice is to low....

And sorry for my bad English !

**Comment by DarkGuardsman** [comment]
Your English is fine so no fear on that :). As far as I understand some linux version of java do not include javafx even in java 8. Recently we had this issue with our build server and @dmodoomsirius has to install a different version of open jdk in order to get it working. I assume this is the same problem but once @Pwalne turns up he can just patch the existing version. Not sure why javafx code is included in the first place since minecraft used open gl and awt for all GUIs.

**Comment by BrokenFire** [comment]
Okay, thank!  I will wait with impatience the patch !

And keep going, your mods are great !

**Comment by Pwalne** [comment]
The patch has been deployed. It no longer uses javax lib, version is 0.29, see CursePage for details.
Thank you for the report.
